### ISSUE TITLE
silence detection using cutoff on the acoustic probabilities

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#156]
I'm using the recognizer for real time transcription and I've noticed that even when the user don't speak the recognizer outputs some gibberish characters...I assume I can fix it using some cutoff probability of the acoustic model right?

**Comment by kuke** [comment]
@alanbekker You can try. But I'm a bit worried about the performance. The white space or blank id should bear the maximum probability when the user speaks noting, otherwise other characters will appear as what you saw. Only when figuring out a way to increase the  probability of blank/space and decrease the probability of other characters, you can solve this problem.
