### ISSUE TITLE
why low test WER on CHiME, training on librispeech Acoustic Model

### ISSUE THREAD

**Issue by lifelongeek** [PaddlePaddle/DeepSpeech#157]
Librispeech provides fairly large amounts of speech (960hour) which is recorded from various recording environment. So I expect training acoustic model on this corpus will also works for speech in another domain, such as CHiME-3.

For acoustic model, deepspeech model is trained with librispeech corpus.
For language model, 4-gram (from http://www.openslr.org/11/) is used.

It achieve 7.6% WER on test-clean, 24.8% WER on test-other.

However, this model is not working to recognize CHiME-3 data.

Clean evaluation dataset got WER 64.2%, Cafe-noise evaluation dataset got 83.7% WER.

What could be the possible reason for degradation?

**Comment by kuke** [comment]
@gmkim90 Our experiment also shows that the model trained from LibriSpeech performs bad on CHiME data. Maybe this is because the LibriSpeech data is too clean and ideal compared to the CHiME data, resulting the trained model lacking of the capacity to recognize the latter, which is recorded in the noisy public environment.

**Comment by gmkim90** [comment]
I agree with your opinion for CHiME noisy data. 
However, when I test on CHiME-3 clean dataset, which is WSJ0, it achieve 64.2% WER.
