### ISSUE TITLE
send only audio features and not the audio data itself to the server for decoding 

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#159]
We are wondering if it is possible to extract the audio features locally and then send only the features instead of audio data. Will that reduce the amount of data needed to send. In other end, is the feature data size significantly smaller than the audio data itself?

**Comment by kuke** [comment]
It is possible to send the features instead of audio data, but it is not always true that the size of feature data will be smaller. The default feature in DS2 is the power spectrum, whose size is equal to the that of the original data for one audio segment (N data points in time domain produces N data points in frequency domain in FFT). But considering that there is overlap between two consecutive segments, the size of feature data would be larger for a complete utterance actually.

**Comment by cogmeta** [comment]
Thank you so much for your reply @kuke.
